---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 每個儲存驅動程式都有一組不同的選項、您可以在建立磁碟區時指定、以自訂結果。請參閱下方、以瞭解適用於您所設定儲存系統的選項。 
---
= 驅動程式專屬的Volume選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個儲存驅動程式都有一組不同的選項、您可以在建立磁碟區時指定、以自訂結果。請參閱下方、以瞭解適用於您所設定儲存系統的選項。

在磁碟區建立作業期間使用這些選項非常簡單。在 CLI 操作期間使用運算子提供選項和值 `-o`。這會覆寫Json組態檔中的任何等效值。



== 選購的選購配備ONTAP

NFS ， iSCSI 和 FC 的 Volume Create 選項包括：

[cols="2*"]
|===
| 選項 | 說明 


| `size`  a| 
Volume的大小、預設為1 GiB。



| `spaceReserve`  a| 
精簡或完整配置磁碟區、預設為精簡。有效值為 `none`（精簡配置）和 `volume`（完整配置）。



| `snapshotPolicy`  a| 
這會將快照原則設定為所需的值。預設值為 `none`、表示不會自動為磁碟區建立任何快照。除非您的儲存管理員修改，否則所有 ONTAP 系統上都會有一個名為「預設」的原則，該原則會建立並保留六個小時，兩個每日快照和兩個每週快照。瀏覽到磁碟區任何目錄中的目錄、即可恢復快照中保留的資料 `.snapshot`。



| `snapshotReserve`  a| 
這會將快照保留設定為所需的百分比。預設值為無值、表示ONTAP 如果您已選取snapshotPolicy、將選取snapshotReserve（通常為5%）、如果snapshotPolicy為無、則選取0%。您可以在組態檔中為所有ONTAP 的支援項目設定預設的snapshotReserve值、也可以將其用作所有ONTAP 不支援ONTAP-NAS-經濟功能的支援項目、作為所有支援項目的磁碟區建立選項。



| `splitOnClone`  a| 
當複製Volume時、ONTAP 這會導致停止實體複本、立即將其從父複本分割開來。預設值為 `false`。部分複製磁碟區的使用案例、最好是在建立時立即將複本從父複本分割出來、因為不太可能有提高儲存效率的機會。例如、複製空資料庫可節省大量時間、但儲存成本卻很少、因此最好立即分割複本。



| `encryption`  a| 
在新磁碟區上啟用 NetApp Volume Encryption （ NVE ）；預設為 `false`。必須在叢集上授權並啟用NVE、才能使用此選項。

如果在後端啟用 NAE 、則 Trident 中配置的任何 Volume 都將啟用 NAE 。

如需更多資訊、請參閱link:../trident-reco/security-reco.html["Trident 如何與 NVE 和 NAE 搭配運作"]：。



| `tieringPolicy`  a| 
設定要用於磁碟區的分層原則。這會決定資料在非作用中（冷）時是否移至雲端層。

|===
下列其他選項適用於NFS * Only *：

[cols="2*"]
|===
| 選項 | 說明 


| `unixPermissions`  a| 
這會控制Volume本身的權限設定。依預設、權限將設為、或以數字表示法 0755 設定 ``---rwxr-xr-x`、並 `root`將成為擁有者。文字或數字格式皆可運作。



| `snapshotDir`  a| 
將此設定為 `true`可讓 `.snapshot`存取該 Volume 的用戶端看到目錄。預設值為 `false`、表示預設會停用目錄的可見度 `.snapshot`。有些映像（例如正式的 MySQL 映像）在目錄可見時無法正常運作 `.snapshot`。



| `exportPolicy`  a| 
設定要用於磁碟區的匯出原則。預設值為 `default`。



| `securityStyle`  a| 
設定用於存取磁碟區的安全樣式。預設值為 `unix`。有效值為 `unix`和 `mixed`。

|===
下列其他選項僅適用於iSCSI *：

[cols="2*"]
|===
| 選項 | 說明 


| `fileSystemType` | 設定用於設定iSCSI磁碟區格式的檔案系統。預設值為 `ext4`。有效值爲 `ext3`、 `ext4`和 `xfs`。 


| `spaceAllocation` | 將此設定為 `false`會關閉 LUN 的空間分配功能。預設值為 `true`、表示當磁碟區空間不足且磁碟區中的 LUN 無法接受寫入時、 ONTAP 會通知主機。此選項也可讓ONTAP 支援功能在主機刪除資料時自動回收空間。 
|===


=== 範例

請參閱下列範例：

* 建立10GiB Volume：
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* 使用快照建立100GiB磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* 建立已啟用setuid位元的磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小Volume大小為20MiB。

如果未指定快照保留、且快照原則為 `none`、則 Trident 會使用 0% 的快照保留。

* 建立沒有快照原則且無快照保留的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* 建立不含快照原則的磁碟區、以及自訂快照保留10%的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* 建立具有快照原則和10%自訂快照保留的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* 使用快照原則建立磁碟區，並接受 ONTAP 的預設快照保留（通常為 5% ）：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element軟體Volume選項

元素軟體選項會顯示與磁碟區相關的服務品質（QoS）原則大小和品質。建立磁碟區時、會使用命名法指定與磁碟區相關的 QoS 原則 `-o type=service_level`。

使用元素驅動程式定義QoS服務層級的第一步、是建立至少一種類型、並在組態檔中指定與名稱相關的最小、最大和尖峰IOPS。

其他元素軟體磁碟區建立選項包括：

[cols="2*"]
|===
| 選項 | 說明 


| `size`  a| 
Volume 的大小、預設為 1GiB 或組態項目 ...「預設值」： ｛ "size" ： "5G" ｝ 。



| `blocksize`  a| 
使用512或4096、預設為512或組態項目預設BlockSizes。

|===


=== 範例

請參閱下列QoS定義範例組態檔：

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
在上述組態中、我們有三種原則定義：銅級、銀級和金級。這些名稱為任意名稱。

* 建立10GiB Gold Volume：
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 建立100GiB銅級磁碟區：
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

