---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: '瞭解如何使用執行後端管理作業 `kubectl`。' 
---
= 以KECBECVL執行後端管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解如何使用執行後端管理作業 `kubectl`。



== 刪除後端

刪除 `TridentBackendConfig`後、您會指示 Trident 刪除 / 保留後端（根據 `deletionPolicy`）。若要刪除後端、請確定已 `deletionPolicy`設定為刪除。若要僅刪除 `TridentBackendConfig`、請確定已 `deletionPolicy`設定為保留。這可確保後端仍存在、並可使用進行管理 `tridentctl`。

執行下列命令：

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Trident 不會刪除使用中的 Kubernetes 機密 `TridentBackendConfig`。Kubernetes使用者負責清除機密。刪除機密時必須小心。只有在後端未使用機密時、才應刪除這些機密。



== 檢視現有的後端

執行下列命令：

[listing]
----
kubectl get tbc -n trident
----
您也可以執行 `tridentctl get backend -n trident`或 `tridentctl get backend -o yaml -n trident`取得存在的所有後端清單。此清單也會包含使用建立的後端 `tridentctl`。



== 更新後端

更新後端可能有多種原因：

* 儲存系統的認證資料已變更。若要更新認證、必須更新物件中使用的 Kubernetes Secret `TridentBackendConfig` 。Trident 會使用提供的最新認證、自動更新後端。執行下列命令以更新Kubernetes Secret：
+
[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* 需要ONTAP 更新參數（例如使用的SVM名稱）。
+
** 您可以使用下列命令、直接透過 Kubernetes 更新 `TridentBackendConfig`物件：
+
[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
** 或者、您也可以使用下列命令變更現有的 `TridentBackendConfig` CR ：
+
[listing]
----
kubectl edit tbc <tbc-name> -n trident
----




[NOTE]
====
* 如果後端更新失敗、後端仍會繼續維持其最後已知的組態。您可以執行或 `kubectl describe tbc <tbc-name> -n trident`來檢視記錄、以判斷原因 `kubectl get tbc <tbc-name> -o yaml -n trident`。
* 識別並修正組態檔的問題之後、即可重新執行update命令。


====