---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: 您可以使用 Trident 安裝程式自訂部署。 
---
= 自訂tridentctl安裝
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Trident 安裝程式自訂安裝。



== 深入瞭解安裝程式

Trident 安裝程式可讓您自訂屬性。例如，如果您已將 Trident 映像複製到私有儲存庫，則可以使用指定映像名稱 `--trident-image`。如果您已將 Trident 映像以及所需的 CSI sidecar 映像複製到私有儲存庫，最好使用採用格式的交換器 `<registry FQDN>[:port]`來指定該儲存庫的位置 `--image-registry`。


IMPORTANT: 在私有儲存庫中安裝 Trident 時、如果您使用 `--image-registry`交換器來指定儲存庫位置、請勿在儲存庫路徑中使用 `/netapp/`。例如： `./tridentctl install --image-registry <image-registry> -n <namespace>`

如果您使用 Kubernetes 的發佈版本， `kubelet`將其資料保留在一般路徑以外的路徑上 `/var/lib/kubelet`，您可以使用來指定替代路徑 `--kubelet-dir`。

如果您需要自訂安裝、而不需要安裝程式的引數允許、也可以自訂部署檔案。使用此 `--generate-custom-yaml`參數會在安裝程式的目錄中建立下列 YAML 檔案 `setup`：

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


產生這些檔案之後、您可以根據需求加以修改、然後使用來 `--use-custom-yaml`安裝自訂部署。

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----