---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: '您可以使用安裝 Trident `tridentctl` 。此程序適用於 Trident 所需的容器映像儲存在私有登錄中或不儲存在私有登錄中的安裝。' 
---
= 使用tridentctl安裝
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用安裝 Trident `tridentctl` 。此程序適用於 Trident 所需的容器映像儲存在私有登錄中或不儲存在私有登錄中的安裝。若要自訂您的 `tridentctl`部署、請參閱link:kubernetes-customize-deploy-tridentctl.html["自訂試用部署"]。



== Trident 25.02 的重要資訊

* 您必須閱讀下列有關 Trident 的重要資訊。 *

.<strong> 的 Trident </strong> 相關資訊
[%collapsible%open]
====
* Kubernetes 1.27 現在支援 Trident 。升級Kubernetes之前先升級Trident。
* Trident 嚴格強制在 SAN 環境中使用多重路徑組態、建議在 multipath.conf 檔案中使用值 `find_multipaths: no`。
+
在 multipath.conf 檔案中使用非多重路徑組態或使用 `find_multipaths: yes`或 `find_multipaths: smart`值、將會導致掛載失敗。Trident 建議自 2007 年 21 月 1 日起使用 `find_multipaths: no`。



====


== 使用安裝 Trident `tridentctl`

請檢閱link:../trident-get-started/kubernetes-deploy.html["安裝總覽"]以確保您符合安裝先決條件、並為您的環境選擇正確的安裝選項。

.開始之前
在開始安裝之前、請先登入 Linux 主機、並確認其正在管理工作中的主機、link:requirements.html["支援的Kubernetes叢集"^]以及您是否擁有必要的 Privileges 。


NOTE: 使用 OpenShift 時、請使用 `oc`而非 `kubectl`後續所有範例、並先執行或 `oc login -u kube-admin`以 * 系統： admin* 的身分登入 `oc login -u system:admin`。

[%collapsible%open]
====
. 驗證Kubernetes版本：
+
[listing]
----
kubectl version
----
. 驗證叢集管理員權限：
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. 確認您可以啟動使用Docker Hub映像的Pod、並透過Pod網路連線至儲存系統：
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== 步驟1：下載Trident安裝程式套件

Trident 安裝程式套件會建立 Trident Pod 、設定用於維持其狀態的 CRD 物件、並初始化 CSI 側板、以執行資源配置及將磁碟區附加至叢集主機等動作。從下載並解壓縮最新版本link:https://github.com/NetApp/trident/releases/latest["GitHub的_Assets區段"^]的Trident 安裝程式。在範例中、使用您所選的 Trident 版本更新 _<XX.XX.x.tar.gz>_ Trident 。

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.02.0/trident-installer-25.02.0.tar.gz
tar -xf trident-installer-25.02.0.tar.gz
cd trident-installer
----


== 步驟 2 ：安裝 Trident

執行命令、在所需的命名空間中安裝 Trident `tridentctl install` 。您可以新增其他引數來指定映像登錄位置。

[role="tabbed-block"]
====
.標準模式
--
[listing]
----
./tridentctl install -n trident
----
--
.一個登錄中的映像
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.02 --trident-image <your-registry>/trident:25.02.0
----
--
.不同登錄中的映像
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.02 --trident-image <your-registry>/trident:25.02.0
----
--
====
您的安裝狀態應該類似這樣。

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.02.0
INFO Trident installation succeeded.
....
----


== 驗證安裝

您可以使用 Pod 建立狀態或來驗證您的安裝 `tridentctl`。



=== 使用Pod建立狀態

您可以檢閱建立的 Pod 狀態、確認 Trident 安裝是否已完成：

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: 如果安裝程式未成功完成、或 `trident-controller-<generated id>` (`trident-csi-<generated id>`版本早於 23.01 ）沒有 * 執行 * 狀態、表示平台尚未安裝。使用 `-d` link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["開啟偵錯模式"]並疑難排解問題。



=== 使用 `tridentctl`

您可以使用 `tridentctl`檢查已安裝的 Trident 版本。

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.02.0        | 25.02.0        |
+----------------+----------------+
----


== 組態範例

以下範例提供使用安裝 Trident 的範例組態 `tridentctl`。

.Windows 節點
[%collapsible]
====
若要啟用 Trident 在 Windows 節點上執行：

[listing]
----
tridentctl install --windows -n trident
----
====
.強制分離
[%collapsible]
====
如需強制分離的詳細資訊、請link:..trident-get-started/kubernetes-customize-deploy.html["自訂Trident操作員安裝"]參閱。

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====